# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
PUT http://localhost:8012/passengers
Accept: application/json

[
{ "flight": "AA1231", "date": "2020-11-11", "firstName": "Jan", "lastName": "Kowalski", "status": "NEW" },
{ "flight": "AA1231", "date": "2020-11-11", "firstName": "Marian", "lastName": "Kowalski", "status": "NEW" },
{ "flight": "AA1231", "date": "2020-11-11", "firstName": "Krystian", "lastName": "Kowalski", "status": "NEW" },
{ "flight": "AA1231", "date": "2020-11-11", "firstName": "Paweł", "lastName": "Kowalski", "status": "NEW" },
{ "flight": "AA1231", "date": "2020-11-11", "firstName": "Piotr", "lastName": "Kowalski", "status": "NEW" },
{ "flight": "AA1231", "date": "2020-11-11", "firstName": "Włodzimierz", "lastName": "Nowak", "status": "NEW" }
]

###

PUT http://localhost:8012/passengers
Accept: application/json

[{ "flight": "AA1231", "date": "2020-11-11", "firstName": "Jan", "lastName": "Kowalski", "status": "NEW" }]

###

PUT http://localhost:8012/airlines
Accept: application/json

{"name": "Polskie Linie Lotnicze LOT", "abbreviation": "LO"}

###

PUT http://localhost:8012/flight
Accept: application/json

{"flightNumber": "LO24", "date": "2020-01-22", "destination": "Paris", "type": "PASSANGER", "direction": "FROM"}

###

PUT http://localhost:8012/flight
Accept: application/json

{"flightNumber": "LO26", "date": "2020-01-22", "destination": "London", "type": "PASSANGER", "direction": "TO"}

